// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWh4Z032zNEwy6EOh3jHdI-GYqrmNSVU',
    appId: '1:80089306082:android:9c54638311c94b18551fbb',
    messagingSenderId: '80089306082',
    projectId: 'padariavinhos-1f842',
    databaseURL: 'https://padariavinhos-1f842-default-rtdb.firebaseio.com',
    storageBucket: 'padariavinhos-1f842.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg516qelWCEU7RiQA29LiFA67WVPIoHjw',
    appId: '1:80089306082:ios:8d52534ff0067813551fbb',
    messagingSenderId: '80089306082',
    projectId: 'padariavinhos-1f842',
    databaseURL: 'https://padariavinhos-1f842-default-rtdb.firebaseio.com',
    storageBucket: 'padariavinhos-1f842.firebasestorage.app',
    iosBundleId: 'com.example.padariavinhos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nySkaHxrvRkd5elV0qLN5HeFWC15cDo',
    appId: '1:80089306082:web:ccee7b65a332d5b1551fbb',
    messagingSenderId: '80089306082',
    projectId: 'padariavinhos-1f842',
    authDomain: 'padariavinhos-1f842.firebaseapp.com',
    databaseURL: 'https://padariavinhos-1f842-default-rtdb.firebaseio.com',
    storageBucket: 'padariavinhos-1f842.firebasestorage.app',
    measurementId: 'G-BWED7ETF50',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_nySkaHxrvRkd5elV0qLN5HeFWC15cDo',
    appId: '1:80089306082:web:79e24c7fc3411227551fbb',
    messagingSenderId: '80089306082',
    projectId: 'padariavinhos-1f842',
    authDomain: 'padariavinhos-1f842.firebaseapp.com',
    databaseURL: 'https://padariavinhos-1f842-default-rtdb.firebaseio.com',
    storageBucket: 'padariavinhos-1f842.firebasestorage.app',
    measurementId: 'G-JSR6LJTM4S',
  );

}