# ios/Podfile

platform :ios, '13.0'   # ✅ mínimo iOS 13

use_frameworks! :linkage => :static
use_modular_headers!

# CocoaPods analytics disable
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
end
